export const DTO_RETRIES = 4;
export const DTO_RETRY_INTERVAL = 4; // Every Nth Pole resend the request
export const DTO_POLL_TIME = 500;

export const enum BoardSquareContent {
  Letter = 0,
  LetterMultiplier,
  WordMultiplier,
}

export const grid_size: number = 15;

export const tiles: string[] = [
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'B',
  'B',
  'C',
  'C',
  'D',
  'D',
  'D',
  'D',
  'E',
  'E',
  'E',
  'E',
  'E',
  'E',
  'E',
  'E',
  'E',
  'E',
  'E',
  'E',
  'F',
  'F',
  'G',
  'G',
  'G',
  'H',
  'H',
  'I',
  'I',
  'I',
  'I',
  'I',
  'I',
  'I',
  'I',
  'I',
  'J',
  'K',
  'L',
  'L',
  'L',
  'L',
  'M',
  'M',
  'N',
  'N',
  'N',
  'N',
  'N',
  'N',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'P',
  'P',
  'Q',
  'R',
  'R',
  'R',
  'R',
  'R',
  'R',
  'S',
  'S',
  'S',
  'S',
  'T',
  'T',
  'T',
  'T',
  'T',
  'T',
  'U',
  'U',
  'U',
  'U',
  'V',
  'V',
  'W',
  'W',
  'X',
  'Y',
  'Y',
  'Z',
  '?',
  '?',
];

export const bonus_letter_tiles: Map<string, number> = new Map([
  ['E', 1],
  ['A', 1],
  ['I', 1],
  ['O', 1],
  ['N', 1],
  ['R', 1],
  ['T', 1],
  ['L', 1],
  ['S', 1],
  ['U', 1],
  ['D', 2],
  ['G', 2],
  ['B', 3],
  ['C', 3],
  ['M', 3],
  ['P', 3],
  ['F', 4],
  ['H', 4],
  ['V', 4],
  ['W', 4],
  ['Y', 4],
  ['K', 5],
  ['J', 8],
  ['X', 8],
  ['Q', 10],
  ['Z', 10],
  ['?', 0],
]);

export enum SquareValue {
  NONE,
  DW,
  TW,
  DL,
  TL
};

export const squareValues: Map<string, SquareValue> = new Map([
  ['0,3', SquareValue.DL],
  ['0,11', SquareValue.DL],
  ['1,5', SquareValue.TL],
  ['1,9', SquareValue.TL],
  ['2,6', SquareValue.DL],
  ['2,8', SquareValue.DL],
  ['3,0', SquareValue.DL],
  ['3,7', SquareValue.DL],
  ['3,14', SquareValue.DL],
  ['5,1', SquareValue.TL],
  ['5,5', SquareValue.TL],
  ['5,9', SquareValue.TL],
  ['5,13', SquareValue.TL],
  ['6,2', SquareValue.DL],
  ['6,6', SquareValue.DL],
  ['6,8', SquareValue.DL],
  ['6,12', SquareValue.DL],
  ['7,3', SquareValue.DL],
  ['7,11', SquareValue.DL],
  ['8,2', SquareValue.DL],
  ['8,6', SquareValue.DL],
  ['8,8', SquareValue.DL],
  ['8,12', SquareValue.DL],
  ['9,1', SquareValue.TL],
  ['9,5', SquareValue.TL],
  ['9,9', SquareValue.TL],
  ['9,13', SquareValue.TL],
  ['11,0', SquareValue.DL],
  ['11,7', SquareValue.DL],
  ['11,14', SquareValue.DL],
  ['12,6', SquareValue.DL],
  ['12,8', SquareValue.DL],
  ['13,5', SquareValue.TL],
  ['13,9', SquareValue.TL],
  ['14,3', SquareValue.DL],
  ['14,11', SquareValue.DL],
  ['0,0', SquareValue.TW],
  ['0,7', SquareValue.TW],
  ['0,14', SquareValue.TW],
  ['1,1', SquareValue.DW],
  ['1,13', SquareValue.DW],
  ['2,2', SquareValue.DW],
  ['2,12', SquareValue.DW],
  ['3,3', SquareValue.DW],
  ['3,11', SquareValue.DW],
  ['4,4', SquareValue.DW],
  ['4,10', SquareValue.DW],
  ['7,0', SquareValue.TW],
  ['7,7', SquareValue.DW],
  ['7,14', SquareValue.TW],
  ['10,4', SquareValue.DW],
  ['10,10', SquareValue.DW],
  ['11,3', SquareValue.DW],
  ['11,11', SquareValue.DW],
  ['12,2', SquareValue.DW],
  ['12,12', SquareValue.DW],
  ['13,1', SquareValue.DW],
  ['13,13', SquareValue.DW],
  ['14,0', SquareValue.TW],
  ['14,7', SquareValue.TW],
  ['14,14', SquareValue.TW],
]);

export type BoardSquare = [string, number, number];
export type BoardRow = BoardSquare[];
export type Board = BoardRow[];

const s: BoardSquare = ['', 0, 0];
const r: BoardRow = [s, s, s, s, s, s, s, s, s, s, s, s, s, s, s];
export const defaultBoard: Board = [r, r, r, r, r, r, r, r, r, r, r, r, r, r, r];
